services:
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: